### ISSUE TITLE
rp2 self.dev_platform

### ISSUE THREAD

**Issue by gide2578** [Carglglz/upydevice#2]
https://github.com/Carglglz/upydevice/blob/45e858cef100276e096925d95ebecbf9465505ed/upydevice/serialdevice.py#L386

serialdevice.py, branch develop, line 386 : 
`if self.dev_platform != 'pyboard' and self.dev_platform != 'rp2':`

Thanks again for the rp2 support !

**Comment by Carglglz** [comment]
ups 😕 
thanks for reporting 👍
